os: osx
#osx_image: xcode9.3       # for using jdk8 when building for Android
osx_image: xcode9.4       # for osx xcode version
branches:
  - staging

jobs:
  include:
    - stage: print_versions
      language: node_js
      node_js: ["8"]
      script:
        - uname -a
        - xcodebuild -version
        - java -version
        - node --version
        - npm -version

    - stage: setup_all
      language: node_js
      node_js: ["8"]
      cache: npm
      script:
        - npm install

    - stage: build_ios
      cache: npm
      script:
        - cd ios
        - pod install
        - cd ..
        - |
          xcodebuild \
            -project ios/MobileApp.xcodeproj \
            -UseNewBuildSystem=NO \
            -scheme MobileApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            -quiet


    - stage: test_on_ios
      language: node_js
      node_js: node_js
      cache: npm
      script:
        - npm run test
  
stages:
  - setup_all
  - build_ios