os: osx
osx_image: xcode9.4
node_js:
  - 8.14.1

jobs:
  include:
    - stage: build and deploy ios appetize release
      language: objective-c
      install: 
        - npm install
        - cd ios
        - pod --no-ansi install
      before_script:
        - "./scripts/versions.sh"
      # - "./scripts/prepare-detox-ci-req.sh"
      script:
        - pwd
        - |
          xcodebuild \
            -workspace ios/MobileApp.xcworkspace \
            -scheme MobileApp \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            -quiet
      # test
      #   - npm run test

    - stage: test depoly
      before_script:
        - openssl aes-256-cbc -K $encrypted_5ada4aafeac8_key -iv $encrypted_5ada4aafeac8_iv -in deploy_key.enc -out ./deploy_key -d
      script:
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ls
        - pwd
        - $encrypted_5478faad

stages:
  - test deploy
  - build and deploy ios appetize release