os: osx
#osx_image: xcode9.3       # for using jdk8 when building for Android
osx_image: xcode9.4       # for osx xcode version
language: objective-c
node_js: ["8.14.1"]

branches:
  only:
    - staging

before_install:
  - ./scripts/versions.sh

install:
  - ./scripts/prepare-detox-req.sh
  - npm install

#ios build
script:
  - cd ios
  - pod --no-ansi install
  - cd ..
  - |
    xcodebuild \
      -workspace ios/MobileApp.xcworkspace \
      -scheme MobileApp \
      -configuration Debug \
      -sdk iphonesimulator \
      -derivedDataPath ios/build \
      -quiet

after_success:
  - npm run test
  
