os: linux
dist: xenial
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
licenses:
  - '.+'
install:
  - nvm install 8.14.1
  - npm install
script:
  - cd android/
  - ./gradlew assembleRelease
