os: osx
#osx_image: xcode9.3       # for using jdk8 when building for Android
osx_image: xcode9.4       # for osx xcode version
node_js: ["8"]
language: node_js


branches:
  only:
    - staging

before_install:
  - echo "======= START::Versions List::START ========"
  - uname -a
  - brew --version
  - xcodebuild -version
  - java -version
  - node --version
  - npm -version
  - echo "========= END::Versions List::END =========="

install:
  - npm install

#ios build
script:
  - cd ios
  - pod --no-ansi install
  - cd ..
  - |
    xcodebuild \
      -project ios/MobileApp.xcodeproj \
      -UseNewBuildSystem=NO \
      -scheme MobileApp \
      -configuration Debug \
      -sdk iphonesimulator \
      -derivedDataPath ios/build \
      -quiet

after_success:
  - npm run test
  
