os: linux
dist: xenial
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_install:
  - echo > $HOME/.android/repositories.cfg
  - yes | sdkmanager --licenses  --verbose
install:
  - nvm install 8.14.1
  - npm install
script:
  - cd android/
  - ./gradlew assembleRelease
  - ls -laht
