os: osx
osx_image: xcode9.4

stages:
  - Build iOS

jobs:
  include:
    - stage: Build iOS
      language: node_js
      node_js:
        - 8.14.1
      env: app_ios=MobileApp.app_$TRAVIS_JOB_NUMBER.zip
      before_install:
        - ls -l
        - openssl aes-256-cbc -K $encrypted_acf840ecd253_key -iv $encrypted_acf840ecd253_iv -in deploy_key.enc -out deploy_key -d
      install:
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - ssh-add ./deploy_key
        - ssh -o "StrictHostKeyChecking no" $var_799cfba7 "$var2 $var3/$TRAVIS_JOB_NUMBER"
        - npm install
        - cd ios
        - pod install
        - cd ..
      script:
        - |
          xcodebuild \
            -workspace ios/MobileApp.xcworkspace \
            -scheme MobileApp \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            -quiet
      after_script:
        - find ios/build/ -type d -maxdepth 5 | grep MobileApp.app
        - zip -qr $app_ios $var1
        - ls -lh *zip
        - scp -o "StrictHostKeyChecking no" $app_ios "$var_799cfba7:$var3/$TRAVIS_JOB_NUMBER"

    - stage: android
      language: java
      jdk: oraclejdk9
      script:
        - which java
        - java -version
      after_success:
        - find android/app/outputs/apk/ -type f | grep apk