stages:
  - name: demo
    if: branch = tools/travis-ci
  - name: build ios
    if: branch IN (master, staging)
  - name: build android
    if: branch IN (master, staging, tools/travis-ci)

jobs:
  include:
    - stage: demo
      env:
        - app_ios_prod=$(tmp="MobileApp.app_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_prod.zip" && tmp=${tmp//\//-} && echo $tmp)
        - app_ios_staging=$(tmp="MobileApp.app_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_app_ios_staging.zip" && tmp=${tmp//\//-} && echo $tmp)
        - dir1=$(tmp1=$TRAVIS_BRANCH && tmp1=${tmp1//\//-} && tmp=$var3"/"$TRAVIS_BUILD_NUMBER"/"$tmp1 && echo $tmp)
        - dir2=$dir1/logs_ios
        - core_sim_log=$HOME/Library/Logs/CoreSimulator/CoreSimulator.log
        - msg=$(echo .git/COMMIT_EDITMSG)
      script:
        - echo $app_ios_prod
        - echo $dir1
        - echo $dir2
        - echo $log_file
        - echo $anrdoid_apk
        - echo $anrdoid_out

    - stage: build ios
      os: osx
      osx_image: xcode9.3
      language: node_js
      node_js:
        - 8.14.1
      env:
        - app_ios_prod=$(tmp="MobileApp.app_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_prod.zip" && tmp=${tmp//\//-} && echo $tmp)
        - app_ios_staging=$(tmp="MobileApp.app_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_app_ios_staging.zip" && tmp=${tmp//\//-} && echo $tmp)
        - dir1=$(tmp1=$TRAVIS_BRANCH && tmp1=${tmp1//\//-} && tmp=$var3"/"$TRAVIS_BUILD_NUMBER"/"$tmp1 && echo $tmp)
        - dir2=$dir1/logs_ios
        - core_sim_log=$HOME/Library/Logs/CoreSimulator/CoreSimulator.log
        - msg=$(echo .git/COMMIT_EDITMSG)
      before_install:
       - echo -n "Starting " > info.txt
       - date >> info.txt
       - date
       - ./scripts/travis_version.rb "src/version.js" "$TRAVIS_JOB_NUMBER" "$TRAVIS_BRANCH"
       - cat src/version.js
       - openssl aes-256-cbc -K $encrypted_acf840ecd253_key -iv $encrypted_acf840ecd253_iv -in deploy_key.enc -out deploy_key -d
       - ls -l
      install:
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - ssh-add ./deploy_key
        - ssh -o "StrictHostKeyChecking no" $var_799cfba7 "$var2 $dir2"
        - npm install
        - cd ios
        - pod install
        - cd ..
      script:
        - ./scripts/build-ios.sh prod $var1 $app_ios_prod
        - ./scripts/build-ios.sh staging $var1 $app_ios_staging
        - ls -laht
      after_success:
        - ls -lahtO
        - ls -lh *zip
        - scp -o "StrictHostKeyChecking no" $app_ios_prod "$var_799cfba7:$dir1"
        - scp -o "StrictHostKeyChecking no" $app_ios_staging "$var_799cfba7:$dir1"
      after_script:
        - pwd
        - ls -lahtO
        - find ios/build/ -type d -maxdepth 5 | grep MobileApp.app
        - git diff > ios.diff
        - scp -o "StrictHostKeyChecking no" ios.diff "$var_799cfba7:$dir2/"
        - scp -o "StrictHostKeyChecking no" $core_sim_log "$var_799cfba7:$dir2/"
        - date
        - "echo \"branch: $TRAVIS_BRANCH\" >> info.txt"
        - "echo \"build dir: $TRAVIS_BUILD_DIR\" >> info.txt"
        - "echo \"commit: $TRAVIS_COMMIT\" >> info.txt"
        - "echo commit message: $msg >> info.txt"
        - "echo; echo >> info.txt"
        - "echo && echo \"Variables:\" && echo >> info.txt"
        - "echo \"------------------------------------------\" >> info.txt"
        - set >> info.txt
        - "echo \"------------------------------------------\" >> info.txt"
        - "echo; echo >> info.txt"
        - "echo -n \"Ending at \" >> info.txt"
        - date >> info.txt
        - df -hs >> info.txt
        - scp -o "StrictHostKeyChecking no" info.txt "$var_799cfba7:$dir1/info_ios.txt"

    - stage: build android
      os: linux
      dist: xenial
      language: android
      jdk: oraclejdk8
      env: 
        - app_ios_prod=$(tmp="MobileApp_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_prod.apk" && tmp=${tmp//\//-} && echo $tmp)
        - app_ios_staging=$(tmp="MobileApp_"$TRAVIS_JOB_NUMBER"_"$TRAVIS_BRANCH"_app_ios_staging.apk" && tmp=${tmp//\//-} && echo $tmp)
        - dir1=$(tmp1=$TRAVIS_BRANCH && tmp1=${tmp1//\//-} && tmp=$var3"/"$TRAVIS_BUILD_NUMBER"/"$tmp1 && echo $tmp)
        - dir2=$dir1/logs_android
      android:
        components:
          - build-tools-27.0.3
          - android-27
      before_install:
        - date
        - openssl aes-256-cbc -K $encrypted_acf840ecd253_key -iv $encrypted_acf840ecd253_iv -in deploy_key.enc -out deploy_key -d
        - which java
        - java -version
        - ls -l
      install:
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - ssh-add ./deploy_key
        - ssh -o "StrictHostKeyChecking no" $var_799cfba7 "$var2 $dir2"
        - nvm install 8.14.1
        - npm install
      script:
        - ./scripts/build-android.sh prod $apk_prod
        - ./scripts/build-android.sh staging $apk_staging
      after_success:
        - ls -lh *apk
        - scp -o "StrictHostKeyChecking no" $apk_prod "$var_799cfba7:$dir1"
        - scp -o "StrictHostKeyChecking no" $apk_staging "$var_799cfba7:$dir1"
      after_script:
        - date
        - ls -lahtO
        - find android/app/outputs/apk/ -type f | grep apk
        - date
