os: osx
osx_image: xcode9.3       # for using jdk8 when building for Android

branches:
  only: ["staging"]

install:
  - npm install
  - cd ios && pod install

  
script:
  - npm run ios
  # - npm run e2e  