os: osx
osx_image: xcode9.3       # for using jdk8 when building for Android
# node_js:
#   - "8"

branches:
  only:
    - staging

jobs:
  include:
    -stage: "Install node dependencies"
    language: node_js
    # node_js: node_js
    cache: npm
    before_script:
      - brew install n
      - n 8.14.1
      - node --version
      - npm -version
    script:
      - npm install

    -stage: "Build for iOS"
    language: node_js
    # node_js: node_js
    cache: npm
    before_script:
      - brew install n
      - n 8.14.1
    script:
      - cd ios
      - pod install
      - cd ..
      - xcodebuild -project ios/MobileApp.xcodeproj -UseNewBuildSystem=NO -scheme MobileApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build


    # -stage: "Test on iOS"
    # language: node_js
    # node_js: node_js
    # cache: npm
    # script:
    #   - npm run test
  
