os: osx
osx_image: xcode9.4
node_js:
- 8.14.1

jobs:
  include:
    - stage: build_ios
      name: "Building iOS"
      language: objective-c
      install: npm i
      before_script:
      - "./scripts/versions.sh"
      - "./scripts/prepare-detox-ci-req.sh"
      script:
      - cd ios
      - pod --no-ansi install
      - cd ..
      - |
        xcodebuild \
          -workspace ios/MobileApp.xcworkspace \
          -scheme MobileApp \
          -configuration Debug \
          -sdk iphonesimulator \
          -derivedDataPath ios/build \
          -quiet
    - stage: test_ios_build
      name: Test iOS Build
      script:
      - npm run test
    - stage: deploy_ios
      name: "Deploy iOS Build"
      before_install:
        - openssl aes-256-cbc -K $encrypted_5ada4aafeac8_key -iv $encrypted_5ada4aafeac8_iv
          -in deploy_key.enc -out ./deploy_key -d
      script:
        - npm run test
    - stage: test_depoly
      name: "Test Deploy"
      script:
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - encrypted_8xet7psch4_key

stages:
  - test_deploy
